### PR TITLE
Change max team capacity

### PR DESCRIPTION
**Pull request by Aleks1908**
Changed the max team capacity to 17 and fix csv to xlsx

### CODE REVIEW

**Review by IvanObreshkov — COMMENTED** [review]
Does it work now?

**Comment by Aleks1908** [comment]
> Does it work now?

The xlsx? or the teams?

**Comment by Aleks1908** [comment]
> > Does it work now?
> 
> The xlsx? or the teams?

I changed the teams cuz the board decided to make max 17 cuz of the random team

**Comment by IvanObreshkov** [comment]
> > Does it work now?
> 
> The xlsx? or the teams?

Th xlsx

**Comment by Aleks1908** [comment]
> > > Does it work now?
> > 
> > 
> > The xlsx? or the teams?
> 
> Th xlsx

The inital creation of the file was in xlsx and i changed it in the front end to csv. So the conversion to cvs was magic xD.

**Pull request merged**
