### PR TITLE
#539 fix https connection error

### LINKED ISSUE #539: [BUG] Error with accessing protected routes still persists
## Brief description:
Despite the changes in the nginx.conf the error is still  there: 
image

## How to achieve it:
Figure it out. Remove the hosts from the nginx.conf and change the logic in the auth.py file.

### PR DESCRIPTION
**Pull request by IvanObreshkov**
resolves #539 

## How to verify:

- [ ] If you have valid certs `IS_OFFLINE` could be set to false, if you have self-signed you should test with `IS_OFFLINE` set to true, because you are going to get an error 
image

- [ ] run docker-compose up --build and and go to https://localhost/v2/logs

### CODE REVIEW

**Comment by mbozhilov-qb** [comment]
> resolves #539
> 
> ## How to verify:
> * [ ]  If you have valid certs `IS_OFFLINE` could be set to false, if you have self-signed you should test with `IS_OFFLINE` set to true, because you are going to get an error
>   image
> * [ ]  run docker-compose up --build and and go to https://localhost/v2/logs

Requests will always work now no matter whether the certs are self-signed or not.

**Comment by asynchroza** [comment]
@IvanObreshkov ping me once you've verified the changes locally and I will approve the PR. Let's get this done once and for all.

**Comment by IvanObreshkov** [comment]
> @IvanObreshkov ping me once you've verified the changes locally and I will approve the PR. Let's get this done once and for all.

@asynchroza  It is working perfectly. I was testing with IS_OFFLINE=true which gave the 502.

**Comment by asynchroza** [comment]
> > @IvanObreshkov ping me once you've verified the changes locally and I will approve the PR. Let's get this done once and for all.
> 
> @asynchroza It is working. I was testing with IS_OFFLINE=true which gave the 502, but I am not sure this is the expected behavior.

When `IS_OFFLINE` is true, the api doesn't start up an https server so hitting the https://py-api:6969 endpoint will result in a dropped connection.

**Comment by IvanObreshkov** [comment]
> > > @IvanObreshkov ping me once you've verified the changes locally and I will approve the PR. Let's get this done once and for all.
> > 
> > 
> > @asynchroza It is working. I was testing with IS_OFFLINE=true which gave the 502, but I am not sure this is the expected behavior.
> 
> When `IS_OFFLINE` is true, the api doesn't start up an https server so hitting the https://py-api:6969 endpoint will result in a dropped connection.

Ok, so are we ready to merge?

**Review by asynchroza — APPROVED** [review]

**Pull request merged**
