### PR TITLE
#466 Update python phony to install poetry package manager

### PR DESCRIPTION
**Pull request by asynchroza**
### How to verify:

Run the phony `make install-python`. 
Verify poetry is installed by running `poetry --version`

### CODE REVIEW

**Comment by asynchroza** [comment]
@IvanObreshkov @Aleks1908 Please, both of you verify this PR by following the instructions in the description.

**Review by IvanObreshkov — CHANGES_REQUESTED** [review]
image

**Comment by asynchroza** [comment]
> image

Should be fixed now. Try once again.

**Comment by IvanObreshkov** [comment]
> > image
> 
> Should be fixed now. Try once again.

Yeah it works, I fixed it myself and tried to push but you were faster :D

**Review by IvanObreshkov — APPROVED** [review]
LGTM

**Review by IvanObreshkov — CHANGES_REQUESTED** [review]
image The script works, but this is not ok.

**Review by IvanObreshkov — APPROVED** [review]
Now it is good 
image

**Review by Aleks1908 — APPROVED** [review]
LGTM

**Pull request merged**
