### PR TITLE
Hackathon teams export

### PR DESCRIPTION
**Pull request by Aleks1908**
Wrote script to export all teams and their participants

### CODE REVIEW

**Review by IvanObreshkov — APPROVED** [review]
Staa kato sa novak

**Review by DemonHashira — APPROVED** [review]
GG

**Review by asynchroza — COMMENTED** [review]
Why didn't we utilize Ninov's work here?

**Comment by Aleks1908** [comment]
> Why didn't we utilize Ninov's work here?

I wanted to experiment :D

**Pull request merged**
